// Mock product data
export const products = [
  {
    id: 1,
    name: "Air Flow Runner",
    description: "Lightweight running shoes with enhanced breathability for maximum comfort during your run.",
    price: 129.99,
    oldPrice: 149.99,
    discount: 15,
    rating: 4.5,
    reviewCount: 127,
    image: "/placeholder.svg?height=400&width=400",
    category: "men",
    isNew: true,
    isFeatured: true,
    colors: ["black", "white", "blue"],
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    createdAt: "2023-10-15T13:45:30",
  },
  {
    id: 2,
    name: "Urban Street Pro",
    description: "Stylish street shoes designed for urban exploration and everyday casual wear.",
    price: 89.99,
    rating: 4.2,
    reviewCount: 95,
    image: "/placeholder.svg?height=400&width=400",
    category: "men",
    isNew: false,
    isFeatured: true,
    colors: ["black", "gray", "white"],
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    createdAt: "2023-09-05T10:22:15",
  },
  {
    id: 3,
    name: "Flex Performance",
    description: "High-performance training shoes with enhanced flexibility for dynamic workouts.",
    price: 119.99,
    oldPrice: 139.99,
    discount: 15,
    rating: 4.7,
    reviewCount: 212,
    image: "/placeholder.svg?height=400&width=400",
    category: "men",
    isNew: true,
    isFeatured: false,
    colors: ["black", "blue", "red"],
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    createdAt: "2023-11-20T08:15:45",
  },
  {
    id: 4,
    name: "Classic Court",
    description: "Timeless tennis-inspired shoes for casual wear with a clean, minimalist design.",
    price: 79.99,
    rating: 4.3,
    reviewCount: 78,
    image: "/placeholder.svg?height=400&width=400",
    category: "men",
    isNew: false,
    isFeatured: true,
    colors: ["white", "green", "black"],
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    createdAt: "2023-08-10T14:30:00",
  },
  {
    id: 5,
    name: "Trail Blazer X",
    description: "Rugged trail shoes designed for off-road adventures and challenging terrains.",
    price: 149.99,
    rating: 4.6,
    reviewCount: 92,
    image: "/placeholder.svg?height=400&width=400",
    category: "men",
    isNew: false,
    isFeatured: false,
    colors: ["brown", "green", "black"],
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    createdAt: "2023-07-15T11:20:30",
  },
  {
    id: 6,
    name: "Cloud Step Elite",
    description: "Ultra-lightweight running shoes with responsive cushioning for a cloud-like feel.",
    price: 159.99,
    oldPrice: 179.99,
    discount: 10,
    rating: 4.8,
    reviewCount: 156,
    image: "/placeholder.svg?height=400&width=400",
    category: "women",
    isNew: true,
    isFeatured: true,
    colors: ["pink", "blue", "white"],
    sizes: ["US 5", "US 6", "US 7", "US 8", "US 9", "US 10"],
    createdAt: "2023-12-01T09:45:00",
  },
  {
    id: 7,
    name: "Glamour Step",
    description: "Fashion-forward athletic shoes combining style and performance for active women.",
    price: 99.99,
    rating: 4.4,
    reviewCount: 87,
    image: "/placeholder.svg?height=400&width=400",
    category: "women",
    isNew: false,
    isFeatured: true,
    colors: ["pink", "purple", "white"],
    sizes: ["US 5", "US 6", "US 7", "US 8", "US 9", "US 10"],
    createdAt: "2023-09-25T16:10:45",
  },
  {
    id: 8,
    name: "Flex Lifestyle",
    description: "Versatile shoes designed for an active lifestyle, offering comfort and style.",
    price: 89.99,
    oldPrice: 99.99,
    discount: 10,
    rating: 4.3,
    reviewCount: 67,
    image: "/placeholder.svg?height=400&width=400",
    category: "women",
    isNew: true,
    isFeatured: false,
    colors: ["black", "pink", "white"],
    sizes: ["US 5", "US 6", "US 7", "US 8", "US 9", "US 10"],
    createdAt: "2023-11-10T14:20:30",
  },
  {
    id: 9,
    name: "Strut Pro",
    description: "Fashion-forward athletic shoes with enhanced arch support and comfort features.",
    price: 119.99,
    rating: 4.5,
    reviewCount: 112,
    image: "/placeholder.svg?height=400&width=400",
    category: "women",
    isNew: false,
    isFeatured: true,
    colors: ["red", "black", "white"],
    sizes: ["US 5", "US 6", "US 7", "US 8", "US 9", "US 10"],
    createdAt: "2023-08-20T10:15:00",
  },
  {
    id: 10,
    name: "Zephyr Walk",
    description: "Lightweight walking shoes designed for all-day comfort and support.",
    price: 79.99,
    rating: 4.2,
    reviewCount: 65,
    image: "/placeholder.svg?height=400&width=400",
    category: "women",
    isNew: false,
    isFeatured: false,
    colors: ["blue", "gray", "pink"],
    sizes: ["US 5", "US 6", "US 7", "US 8", "US 9", "US 10"],
    createdAt: "2023-07-05T11:30:45",
  },
  {
    id: 11,
    name: "Little Explorer",
    description: "Durable and comfortable shoes designed for active kids who love adventures.",
    price: 59.99,
    rating: 4.6,
    reviewCount: 89,
    image: "/placeholder.svg?height=400&width=400",
    category: "kids",
    isNew: true,
    isFeatured: true,
    colors: ["blue", "green", "red"],
    sizes: ["US 1", "US 2", "US 3", "US 4", "US 5", "US 6"],
    createdAt: "2023-12-10T09:00:00",
  },
  {
    id: 12,
    name: "Playground Pro",
    description: "Tough, scuff-resistant shoes perfect for school and playground activities.",
    price: 49.99,
    oldPrice: 59.99,
    discount: 15,
    rating: 4.4,
    reviewCount: 74,
    image: "/placeholder.svg?height=400&width=400",
    category: "kids",
    isNew: false,
    isFeatured: true,
    colors: ["black", "blue", "red"],
    sizes: ["US 1", "US 2", "US 3", "US 4", "US 5", "US 6"],
    createdAt: "2023-09-15T15:20:30",
  },
  {
    id: 13,
    name: "Junior Sprinter",
    description: "Lightweight athletic shoes designed to help young athletes perform their best.",
    price: 69.99,
    rating: 4.5,
    reviewCount: 62,
    image: "/placeholder.svg?height=400&width=400",
    category: "kids",
    isNew: true,
    isFeatured: false,
    colors: ["blue", "green", "black"],
    sizes: ["US 1", "US 2", "US 3", "US 4", "US 5", "US 6"],
    createdAt: "2023-11-05T13:10:00",
  },
  {
    id: 14,
    name: "Tiny Steps First",
    description: "Specially designed shoes for toddlers learning to walk, providing support and stability.",
    price: 39.99,
    rating: 4.7,
    reviewCount: 93,
    image: "/placeholder.svg?height=400&width=400",
    category: "kids",
    isNew: false,
    isFeatured: true,
    colors: ["pink", "blue", "yellow"],
    sizes: ["US 1", "US 2", "US 3", "US 4", "US 5", "US 6"],
    createdAt: "2023-08-01T10:45:15",
  },
  {
    id: 15,
    name: "School Day Comfort",
    description: "Comfortable and practical shoes for everyday school wear with extra durability.",
    price: 54.99,
    oldPrice: 64.99,
    discount: 15,
    rating: 4.3,
    reviewCount: 57,
    image: "/placeholder.svg?height=400&width=400",
    category: "kids",
    isNew: false,
    isFeatured: false,
    colors: ["black", "white", "navy"],
    sizes: ["US 1", "US 2", "US 3", "US 4", "US 5", "US 6"],
    createdAt: "2023-07-20T14:00:30",
  },
]

